stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - echo "Deploy to Nexus repository here."
